/**
 * נתוני זריעה (seed) — נקודת פתיחה כדי שהמערכת תהיה שימושית מהרגע הראשון.
 *
 * ⚠️ מקור הנתונים: מחקר ווב פומבי (אתרי הקבוצה, הודעות לעיתונות, כתבות),
 *    ולא סריקה ישירה של aman-global.com. לכל רשומה יש source_url ו-confidence.
 *    הרצת `npm run scrape:group` תעדכן/תחליף את הנתונים בסריקה אמיתית מהאתר,
 *    ותסמן origin='scrape' עם confidence גבוה יותר.
 */

const AMAN_COMPANIES = 'https://www.aman.co.il/companies/';

// ═══════════════════════════════════════════════════════════════════════
//  חברות בת + שירותים
// ═══════════════════════════════════════════════════════════════════════
export const SUBSIDIARIES = [
  {
    slug: 'aman-group',
    name_he: 'אמן מחשוב (הקבוצה)',
    name_en: 'Aman Group',
    website: 'https://www.aman.co.il/',
    description: 'גוף האם של הקבוצה. מיקור חוץ ושירותי מומחים, השמה וגיוס טכנולוגי, מרכזי מצוינות. כ-4,000 עובדים בישראל ובעולם.',
    domains: ['outsourcing', 'staffing', 'consulting'],
    hq_country: 'IL',
    joined_year: null,
    source_url: 'https://www.aman-global.com/',
    confidence: 0.85,
    services: [
      { slug: 'outsourcing', name_he: 'מיקור חוץ ושירותי מומחים', category: 'consulting',
        keywords: ['outsourcing', 'מיקור חוץ', 'שירותי מומחים', 'צוותי פיתוח', 'staff augmentation'] },
      { slug: 'tech-recruitment', name_he: 'גיוס והשמה טכנולוגית', category: 'hr',
        keywords: ['גיוס', 'השמה', 'recruitment', 'hiring', 'מפתחים', 'תקנים'] },
      { slug: 'managed-teams', name_he: 'צוותים מנוהלים ומרכזי מצוינות', category: 'consulting',
        keywords: ['managed team', 'center of excellence', 'מרכז מצוינות', 'ODC'] },
    ],
  },
  {
    slug: 'eternity',
    name_he: 'איטרניטי (Eternity)',
    name_en: 'Eternity',
    website: 'https://www.eternity-it.co.il/',
    description: 'בית תוכנה לדאטה: BI, אנליטיקה, Big Data, מדע הנתונים ו-ML. מעל 400 מומחי דאטה. ורטיקלים: בנקאות וביטוח, ממשל וביטחון, תעשייה, היי-טק.',
    domains: ['data', 'bi', 'analytics', 'ai'],
    hq_country: 'IL', founded_year: 2008, joined_year: 2016,
    source_url: 'https://www.eternity-it.co.il/',
    confidence: 0.85,
    services: [
      { slug: 'bi-analytics', name_he: 'BI ואנליטיקה', category: 'data',
        keywords: ['BI', 'business intelligence', 'דוחות', 'dashboard', 'Power BI', 'Tableau', 'Qlik'] },
      { slug: 'data-platform', name_he: 'פלטפורמות דאטה ו-Data Warehouse', category: 'data',
        keywords: ['data warehouse', 'data lake', 'Snowflake', 'Databricks', 'ETL', 'Informatica', 'מחסן נתונים'] },
      { slug: 'data-science-ml', name_he: 'מדע הנתונים ולמידת מכונה', category: 'ai',
        keywords: ['machine learning', 'data science', 'מודל חיזוי', 'ML', 'אלגוריתם'] },
      { slug: 'gen-ai', name_he: 'פתרונות GenAI ארגוניים', category: 'ai',
        keywords: ['GenAI', 'LLM', 'בינה מלאכותית', 'AI', 'copilot', 'RAG'] },
      { slug: 'data-governance', name_he: 'ממשל נתונים ואיכות נתונים', category: 'data',
        keywords: ['data governance', 'data quality', 'ממשל נתונים', 'MDM', 'קטלוג נתונים'] },
    ],
  },
  {
    slug: 'aman-cyber-cloud',
    name_he: 'אמן סייבר וענן (לשעבר אשנב)',
    name_en: 'Aman Cyber & Cloud (formerly Eshnav)',
    website: 'https://www.aman.co.il/',
    description: 'תשתיות, ענן וסייבר: אינטגרציה, הגנת מידע, גיבוי ושחזור, DR, אבטחת תשתיות ומיגרציה לענן.',
    domains: ['cyber', 'cloud', 'infrastructure'],
    hq_country: 'IL',
    source_url: AMAN_COMPANIES,
    confidence: 0.7,
    services: [
      { slug: 'cloud-migration', name_he: 'מיגרציה וניהול ענן', category: 'cloud',
        keywords: ['cloud', 'ענן', 'AWS', 'Azure', 'GCP', 'מיגרציה', 'FinOps', 'hybrid cloud'] },
      { slug: 'backup-dr', name_he: 'גיבוי, שחזור והתאוששות מאסון', category: 'infrastructure',
        keywords: ['backup', 'DR', 'disaster recovery', 'גיבוי', 'שחזור', 'רציפות עסקית', 'BCP'] },
      { slug: 'infosec', name_he: 'הגנת מידע ואבטחת תשתיות', category: 'cyber',
        keywords: ['אבטחת מידע', 'סייבר', 'cyber', 'SOC', 'EDR', 'zero trust', 'הגנת סייבר'] },
      { slug: 'it-integration', name_he: 'אינטגרציית IT ותשתיות', category: 'infrastructure',
        keywords: ['אינטגרציה', 'תשתיות', 'datacenter', 'virtualization', 'וירטואליזציה'] },
      { slug: 'compliance-hardening', name_he: 'עמידה ברגולציה והקשחות', category: 'cyber',
        keywords: ['ISO 27001', 'SOC 2', 'רגולציה', 'תקן', 'ביקורת', 'הגנת פרטיות', 'GDPR'] },
    ],
  },
  {
    slug: 'innocom',
    name_he: 'אינוקום (Innocom)',
    name_en: 'Innocom',
    website: 'https://www.innocom.co.il/',
    description: 'זרוע ההפצה (VAD) של הקבוצה: תקשורת, אבטחת מידע וסייבר, ענן ו-Digital Workplace. מפיצה בלעדית של Citrix ו-NetScaler בישראל ובאזור. רכשה את Webiscope.',
    domains: ['distribution', 'cyber', 'networking', 'cloud'],
    hq_country: 'IL', founded_year: 2004, joined_year: 2011,
    source_url: 'https://www.calcalistech.com/ctechnews/article/rjkbu5jxt',
    confidence: 0.8,
    services: [
      { slug: 'security-products', name_he: 'הפצת מוצרי סייבר ואבטחת מידע', category: 'cyber',
        keywords: ['firewall', 'NGFW', 'WAF', 'DLP', 'סייבר', 'רישוי אבטחה'] },
      { slug: 'networking', name_he: 'פתרונות תקשורת ו-ADC', category: 'infrastructure',
        keywords: ['NetScaler', 'ADC', 'load balancer', 'תקשורת', 'SD-WAN', 'רשת'] },
      { slug: 'digital-workplace', name_he: 'Digital Workplace ו-VDI', category: 'infrastructure',
        keywords: ['Citrix', 'VDI', 'עמדות עבודה', 'remote work', 'עבודה מרחוק', 'DaaS'] },
      { slug: 'vendor-support', name_he: 'תמיכה ושירותים מקצועיים לספקים', category: 'consulting',
        keywords: ['support', 'תמיכה', 'professional services', 'הטמעה'] },
    ],
  },
  {
    slug: 'aman-digital',
    name_he: 'אמן דיגיטל (Aman Digital)',
    name_en: 'Aman Digital',
    website: 'https://amandigital.co.il/',
    description: 'סוכנות דיגיטל Full-Service: אסטרטגיה דיגיטלית, UX/UI, פיתוח אתרים ואפליקציות, Low-Code (OutSystems), שיווק דיגיטלי ו-GEO/SEO.',
    domains: ['digital', 'ux', 'marketing', 'low-code'],
    hq_country: 'IL', joined_year: 2016,
    source_url: 'https://amandigital.co.il/company/',
    confidence: 0.85,
    services: [
      { slug: 'ux-ui', name_he: 'עיצוב חוויית משתמש וממשק (UX/UI)', category: 'digital',
        keywords: ['UX', 'UI', 'חוויית משתמש', 'עיצוב', 'design system', 'נגישות'] },
      { slug: 'web-app-dev', name_he: 'פיתוח אתרים ואפליקציות', category: 'digital',
        keywords: ['אתר', 'אפליקציה', 'website', 'mobile app', 'פורטל', 'אזור אישי'] },
      { slug: 'lowcode-outsystems', name_he: 'פיתוח Low-Code ב-OutSystems', category: 'digital',
        keywords: ['OutSystems', 'low code', 'לואו קוד', 'מערכות ליבה', 'דיגיטציה'] },
      { slug: 'digital-strategy', name_he: 'אסטרטגיה דיגיטלית ומחקר', category: 'digital',
        keywords: ['אסטרטגיה דיגיטלית', 'מחקר משתמשים', 'מיפוי מסע לקוח', 'digital transformation'] },
      { slug: 'digital-marketing', name_he: 'שיווק דיגיטלי, SEO ו-GEO', category: 'marketing',
        keywords: ['SEO', 'GEO', 'קמפיין', 'Google Ads', 'Meta', 'שיווק דיגיטלי', 'מיתוג'] },
    ],
  },
  {
    slug: 'kms-lighthouse',
    name_he: 'KMS Lighthouse',
    name_en: 'KMS Lighthouse',
    website: 'https://kmslh.com/',
    description: 'פלטפורמת ניהול ידע ארגוני מבוססת AI למוקדי שירות, סוכנים ולקוחות קצה. נמכרת גם דרך Microsoft Azure Marketplace.',
    domains: ['knowledge-management', 'cx', 'ai'],
    hq_country: 'IL', founded_year: 2012,
    source_url: 'https://kmslh.com/',
    confidence: 0.85,
    services: [
      { slug: 'agent-knowledge', name_he: 'ניהול ידע לנציגי שירות ומכירות', category: 'cx',
        keywords: ['מוקד שירות', 'call center', 'contact center', 'נציגים', 'זמן טיפול', 'AHT'] },
      { slug: 'self-service', name_he: 'שירות עצמי ובוטים מבוססי ידע', category: 'cx',
        keywords: ['שירות עצמי', 'self service', 'chatbot', 'בוט', 'FAQ', 'הפחתת פניות'] },
      { slug: 'knowledge-ai', name_he: 'חיפוש ותשובות מבוססות AI על מאגר הידע', category: 'ai',
        keywords: ['AI', 'GenAI', 'חיפוש חכם', 'RAG', 'knowledge base'] },
      { slug: 'onboarding-training', name_he: 'קליטה והדרכת עובדים חדשים', category: 'cx',
        keywords: ['onboarding', 'הדרכה', 'קליטת עובדים', 'תחלופה', 'training'] },
    ],
  },
  {
    slug: 'asperii',
    name_he: 'אספרי (Asperii)',
    name_en: 'Asperii',
    website: 'https://www.asperii.com/',
    description: 'שותפת ייעוץ Salesforce גלובלית המתמחה ב-Field Service ובניהול כוח אדם בשטח. משווקת מורשית של Salesforce בישראל ושותפת ServiceMax Asset 360.',
    domains: ['crm', 'field-service', 'salesforce'],
    hq_country: 'IL',
    source_url: 'https://www.prnewswire.com/il/news-releases/asperii-announces-3m-investment-from-aman-group-fueling-its-global-expansion-in-the-field-service-market-300804101.html',
    confidence: 0.85,
    services: [
      { slug: 'salesforce-fsl', name_he: 'הטמעת Salesforce Field Service', category: 'crm',
        keywords: ['Field Service', 'FSL', 'טכנאים', 'שירות בשטח', 'dispatch', 'תיאום ביקורים'] },
      { slug: 'salesforce-crm', name_he: 'הטמעת וייעוץ Salesforce CRM', category: 'crm',
        keywords: ['Salesforce', 'CRM', 'מערכת ניהול לקוחות', 'Sales Cloud', 'Service Cloud'] },
      { slug: 'servicemax', name_he: 'ServiceMax / Asset 360 לניהול נכסים', category: 'crm',
        keywords: ['ServiceMax', 'Asset 360', 'ניהול נכסים', 'תחזוקה', 'IoT'] },
      { slug: 'workforce-mgmt', name_he: 'ניהול כוח אדם בשטח ואופטימיזציה', category: 'crm',
        keywords: ['workforce', 'תכנון משאבים', 'אופטימיזציה', 'scheduling', 'מוסך', 'התקנות'] },
    ],
  },
  {
    slug: 'veriest',
    name_he: 'ורייאסט (Veriest)',
    name_en: 'Veriest Solutions',
    website: 'https://www.veriests.com/',
    description: 'בית עיצוב שבבים: תכנון ואימות ASIC/FPGA, Backend ו-DFT, אימות פורמלי ופרוטוטייפינג. כ-150 מהנדסים בישראל, סרביה, הונגריה ובריטניה.',
    domains: ['semiconductor', 'vlsi', 'engineering'],
    hq_country: 'IL', founded_year: 2007, joined_year: 2013,
    source_url: 'https://www.veriests.com/',
    confidence: 0.85,
    services: [
      { slug: 'design-verification', name_he: 'אימות פונקציונלי (DV)', category: 'product',
        keywords: ['verification', 'UVM', 'SystemVerilog', 'אימות', 'DV', 'טייפ-אאוט'] },
      { slug: 'asic-fpga-design', name_he: 'תכנון ASIC ו-FPGA', category: 'product',
        keywords: ['ASIC', 'FPGA', 'RTL', 'שבב', 'chip', 'silicon'] },
      { slug: 'backend-dft', name_he: 'Physical Design, Backend ו-DFT', category: 'product',
        keywords: ['backend', 'physical design', 'DFT', 'place and route', 'tapeout'] },
      { slug: 'formal-verification', name_he: 'אימות פורמלי', category: 'product',
        keywords: ['formal verification', 'אימות פורמלי', 'assertion', 'SVA'] },
    ],
  },
  {
    slug: 'dbfs',
    name_he: 'DBFS',
    name_en: 'DBFS',
    website: 'https://www.dbfs.co.uk/',
    description: 'ייעוץ, אספקה וגיוס לשווקים הפיננסיים מאז 1996. למעלה מ-50 ארגונים פיננסיים גדולים בבריטניה ובאירופה.',
    domains: ['fintech', 'consulting', 'staffing'],
    hq_country: 'UK', founded_year: 1996,
    source_url: 'https://www.dbfs.co.uk/',
    confidence: 0.7,
    services: [
      { slug: 'fin-consulting', name_he: 'ייעוץ טכנולוגי לשווקים פיננסיים', category: 'consulting',
        keywords: ['financial markets', 'trading', 'banking', 'שוק ההון', 'פיננסים'] },
      { slug: 'fin-delivery', name_he: 'אספקת פרויקטים בסקטור הפיננסי', category: 'consulting',
        keywords: ['delivery', 'project', 'פרויקט', 'implementation'] },
      { slug: 'fin-recruitment', name_he: 'גיוס מומחים לשוק הפיננסי', category: 'hr',
        keywords: ['recruitment', 'גיוס', 'contractors', 'מומחים'] },
    ],
  },
  {
    slug: 'deonix',
    name_he: 'DeoniX',
    name_en: 'DeoniX',
    website: 'https://deonix.kz/',
    description: 'מובילה אזורית בקזחסטן ומרכז אסיה ב-Data Management, Digital Workspace ופתרונות ארגוניים. מפיצה ראשית של Informatica, KMS Lighthouse, Citrix ו-NetScaler באזור.',
    domains: ['data', 'distribution', 'enterprise'],
    hq_country: 'KZ', founded_year: 2010,
    source_url: AMAN_COMPANIES,
    confidence: 0.65,
    services: [
      { slug: 'data-management-kz', name_he: 'ניהול נתונים ואינטגרציה (Informatica)', category: 'data',
        keywords: ['Informatica', 'data management', 'MDM', 'integration'] },
      { slug: 'digital-workspace-kz', name_he: 'Digital Workspace אזורי', category: 'infrastructure',
        keywords: ['Citrix', 'NetScaler', 'workspace', 'VDI'] },
      { slug: 'enterprise-solutions-kz', name_he: 'פתרונות ארגוניים למרכז אסיה', category: 'consulting',
        keywords: ['enterprise', 'Kazakhstan', 'Central Asia', 'CIS'] },
    ],
  },
  {
    slug: 'hccm',
    name_he: 'HCCM Consulting',
    name_en: 'HCCM Consulting',
    website: 'https://www.hccm.pt/',
    description: 'חברת ייעוץ IT מליסבון, פורטוגל, פעילה מאז 1995 עם מעל 120 מומחים. ניסיון בבנקאות, ביטוח, שירותים ציבוריים, אנרגיה, קמעונאות, טלקום ותעשייה.',
    domains: ['consulting', 'it-services'],
    hq_country: 'PT', founded_year: 1995,
    source_url: AMAN_COMPANIES,
    confidence: 0.65,
    services: [
      { slug: 'it-consulting-pt', name_he: 'ייעוץ ואספקת IT באירופה', category: 'consulting',
        keywords: ['IT consulting', 'Portugal', 'Europe', 'nearshore'] },
      { slug: 'nearshore-teams', name_he: 'צוותי Nearshore', category: 'consulting',
        keywords: ['nearshore', 'צוותים', 'outsourcing', 'EU'] },
    ],
  },
  {
    slug: 'integral-solutions',
    name_he: 'Integral Solutions',
    name_en: 'Integral Solutions',
    website: 'https://www.integralsolutions.pl/',
    description: 'המפיצה הרשמית של Informatica בפולין. אינטגרציית נתונים, Data Engineering ושירותי ענן.',
    domains: ['data', 'distribution'],
    hq_country: 'PL',
    source_url: AMAN_COMPANIES,
    confidence: 0.65,
    services: [
      { slug: 'informatica-pl', name_he: 'הפצת והטמעת Informatica', category: 'data',
        keywords: ['Informatica', 'ETL', 'data integration', 'Poland'] },
      { slug: 'data-engineering-pl', name_he: 'Data Engineering ושירותי ענן', category: 'data',
        keywords: ['data engineering', 'cloud', 'pipeline'] },
    ],
  },
  {
    slug: 'kiddod',
    name_he: 'כידוד הנדסה (Kiddod)',
    name_en: 'Kiddod Engineering',
    website: null,
    description: 'תכנון וניהול מערכות שינוע חומרים לתעשיות כרייה, נמלי ים ועיבוד מזון.',
    domains: ['engineering', 'industrial'],
    hq_country: 'IL',
    source_url: AMAN_COMPANIES,
    confidence: 0.6,
    services: [
      { slug: 'material-handling', name_he: 'תכנון מערכות שינוע חומרים', category: 'product',
        keywords: ['שינוע', 'material handling', 'conveyor', 'כרייה', 'נמל', 'מסועים'] },
      { slug: 'industrial-pm', name_he: 'ניהול פרויקטים תעשייתיים', category: 'consulting',
        keywords: ['פרויקט תעשייתי', 'הקמה', 'מפעל', 'EPC'] },
    ],
  },
  {
    slug: 'rasner',
    name_he: 'Rasner',
    name_en: 'Rasner',
    website: null,
    description: 'פתרונות תוכנה לשרשרת אספקה — הפחתת עלויות לוגיסטיקה ושיפור רמת השירות ללקוח.',
    domains: ['supply-chain', 'software'],
    hq_country: 'IL',
    source_url: AMAN_COMPANIES,
    confidence: 0.6,
    services: [
      { slug: 'supply-chain-sw', name_he: 'תוכנה לניהול שרשרת אספקה', category: 'product',
        keywords: ['שרשרת אספקה', 'supply chain', 'מלאי', 'inventory', 'לוגיסטיקה', 'WMS'] },
      { slug: 'demand-planning', name_he: 'תכנון ביקושים ואופטימיזציית מלאי', category: 'product',
        keywords: ['demand planning', 'תחזית', 'מלאי', 'forecasting', 'S&OP'] },
    ],
  },
];

// ═══════════════════════════════════════════════════════════════════════
//  קטלוג טריגרים — סימני רכישה
// ═══════════════════════════════════════════════════════════════════════
export const TRIGGER_TYPES = [
  { code: 'funding_round', name_he: 'גיוס הון', name_en: 'Funding round', category: 'financial', base_weight: 0.8, decay_days: 270,
    description: 'החברה גייסה הון — תקציב חדש לפרויקטים טכנולוגיים.',
    keywords: ['גיוס', 'סבב גיוס', 'raised', 'funding', 'Series A', 'Series B', 'Series C', 'השקעה', 'investment'] },
  { code: 'ipo_listing', name_he: 'הנפקה / רישום למסחר', name_en: 'IPO / listing', category: 'financial', base_weight: 0.85, decay_days: 365,
    description: 'הנפקה מחייבת בקרות, דיווח, ממשל נתונים ואבטחת מידע ברמה ציבורית.',
    keywords: ['הנפקה', 'IPO', 'תשקיף', 'רישום למסחר', 'listing', 'בורסה', 'TASE', 'NASDAQ'] },
  { code: 'earnings_growth', name_he: 'צמיחה בדוחות הכספיים', name_en: 'Strong earnings', category: 'financial', base_weight: 0.55, decay_days: 120,
    description: 'צמיחה בהכנסות/רווח — סימן לתקציבי השקעה זמינים.',
    keywords: ['דוח כספי', 'רבעון', 'earnings', 'revenue growth', 'צמיחה', 'הכנסות', 'רווח', 'Q1', 'Q2', 'Q3', 'Q4'] },
  { code: 'cost_efficiency', name_he: 'תוכנית התייעלות / קיצוצים', name_en: 'Cost cutting', category: 'financial', base_weight: 0.6, decay_days: 180,
    description: 'לחץ להתייעלות פותח דלת לאוטומציה, מיקור חוץ והפחתת עלות תפעול.',
    keywords: ['התייעלות', 'קיצוץ', 'פיטורים', 'layoffs', 'cost cutting', 'efficiency', 'צמצום'] },
  { code: 'merger_acquisition', name_he: 'מיזוג או רכישה', name_en: 'M&A', category: 'financial', base_weight: 0.85, decay_days: 365,
    description: 'מיזוג מחייב איחוד מערכות, מיגרציית נתונים, איחוד תשתיות וזהויות.',
    keywords: ['רכישה', 'מיזוג', 'acquisition', 'merger', 'acquired', 'רכשה', 'M&A', 'עסקה'] },
  { code: 'exec_appointment', name_he: 'מינוי בכיר טכנולוגי (CIO/CTO/CDO/CISO)', name_en: 'Tech exec hire', category: 'organizational', base_weight: 0.8, decay_days: 240,
    description: 'מנהל טכנולוגי חדש מגיע עם אג׳נדה ותקציב לשינוי — חלון הזדמנות של 6-12 חודשים.',
    keywords: ['מונה', 'מינוי', 'CIO', 'CTO', 'CDO', 'CISO', 'סמנכ"ל טכנולוגיות', 'סמנכ"ל דיגיטל', 'appointed', 'joins as'] },
  { code: 'hiring_surge_it', name_he: 'גיוס מסיבי בטכנולוגיה', name_en: 'IT hiring surge', category: 'organizational', base_weight: 0.65, decay_days: 150,
    description: 'ריבוי משרות טכנולוגיות פתוחות מעיד על פרויקט גדול — ולעיתים על מחסור בכוח אדם שמיקור חוץ פותר.',
    keywords: ['דרושים', 'משרות', 'hiring', 'open positions', 'מגייסת', 'גיוס עובדים', 'צוות חדש'] },
  { code: 'reorg', name_he: 'שינוי ארגוני / מבנה חדש', name_en: 'Reorganization', category: 'organizational', base_weight: 0.5, decay_days: 180,
    description: 'ריסטרקטורינג מייצר צורך בהתאמת מערכות, הרשאות ותהליכים.',
    keywords: ['ריאורגניזציה', 'שינוי ארגוני', 'מבנה ארגוני', 'restructuring', 'reorg', 'איחוד אגפים'] },
  { code: 'digital_transformation', name_he: 'תוכנית טרנספורמציה דיגיטלית', name_en: 'Digital transformation', category: 'technological', base_weight: 0.8, decay_days: 365,
    description: 'הצהרה על טרנספורמציה = תקציב רב-שנתי לדיגיטל, UX, דאטה ותשתיות.',
    keywords: ['טרנספורמציה', 'digital transformation', 'דיגיטציה', 'מודרניזציה', 'modernization', 'חדשנות'] },
  { code: 'cloud_migration', name_he: 'מעבר לענן', name_en: 'Cloud migration', category: 'technological', base_weight: 0.75, decay_days: 270,
    description: 'מיגרציה לענן גוררת תשתיות, אבטחה, גיבוי, FinOps ודאטה.',
    keywords: ['ענן', 'cloud', 'AWS', 'Azure', 'GCP', 'מיגרציה', 'migration', 'datacenter exit', 'hybrid'] },
  { code: 'ai_initiative', name_he: 'יוזמת AI / GenAI', name_en: 'AI initiative', category: 'technological', base_weight: 0.8, decay_days: 240,
    description: 'יוזמת AI מחייבת תשתית דאטה נקייה, ממשל נתונים, ידע ארגוני ואבטחה.',
    keywords: ['AI', 'בינה מלאכותית', 'GenAI', 'LLM', 'ChatGPT', 'copilot', 'מודל שפה', 'אוטומציה חכמה'] },
  { code: 'data_platform_project', name_he: 'פרויקט דאטה / BI חדש', name_en: 'Data / BI project', category: 'technological', base_weight: 0.8, decay_days: 240,
    description: 'בניית מחסן נתונים או פלטפורמת BI — התאמה ישירה לשירותי דאטה.',
    keywords: ['data warehouse', 'data lake', 'BI', 'מחסן נתונים', 'אנליטיקה', 'Snowflake', 'Databricks', 'דשבורד'] },
  { code: 'core_system_replacement', name_he: 'החלפת מערכת ליבה (ERP/CRM)', name_en: 'Core system replacement', category: 'technological', base_weight: 0.85, decay_days: 365,
    description: 'החלפת ERP/CRM היא פרויקט רב-שנתי עם צורך באינטגרציה, דאטה, UX וניהול ידע.',
    keywords: ['ERP', 'CRM', 'SAP', 'Salesforce', 'Priority', 'Dynamics', 'מערכת ליבה', 'החלפת מערכת', 'הטמעה'] },
  { code: 'new_digital_product', name_he: 'השקת מוצר או אתר/אפליקציה', name_en: 'New product / site launch', category: 'technological', base_weight: 0.7, decay_days: 180,
    description: 'השקה דיגיטלית = צורך ב-UX, פיתוח, תשתית, ביצועים ואבטחה.',
    keywords: ['השקה', 'launch', 'אתר חדש', 'אפליקציה חדשה', 'מוצר חדש', 'ריברנד', 'rebrand', 'אזור אישי'] },
  { code: 'cyber_incident', name_he: 'אירוע סייבר או דליפת מידע', name_en: 'Cyber incident', category: 'technological', base_weight: 0.9, decay_days: 180,
    description: 'אירוע סייבר מייצר תקציב חירום להגנה, גיבוי, DR וביקורת — הטריגר החזק ביותר.',
    keywords: ['מתקפת סייבר', 'דליפה', 'פריצה', 'כופר', 'ransomware', 'breach', 'hack', 'אירוע אבטחה', 'הדלפה'] },
  { code: 'regulatory_pressure', name_he: 'דרישה רגולטורית חדשה', name_en: 'Regulatory requirement', category: 'regulatory', base_weight: 0.75, decay_days: 365,
    description: 'רגולציה חדשה מחייבת עמידה בתקן — פרויקט עם דדליין ותקציב מחייב.',
    keywords: ['רגולציה', 'regulation', 'הגנת הפרטיות', 'GDPR', 'תיקון 13', 'ISO 27001', 'SOC 2', 'באזל', 'הוראת ניהול בנקאי', 'רשות ניירות ערך', 'תקן'] },
  { code: 'audit_finding', name_he: 'ממצא ביקורת / קנס', name_en: 'Audit finding or fine', category: 'regulatory', base_weight: 0.8, decay_days: 270,
    description: 'ממצא ביקורת או קנס מחייב תיקון מיידי — קיצור דרך לתקציב.',
    keywords: ['ביקורת', 'קנס', 'ממצא', 'audit', 'fine', 'עיצום כספי', 'הפרה'] },
  { code: 'market_expansion', name_he: 'התרחבות לשוק או אתר חדש', name_en: 'Market / site expansion', category: 'market', base_weight: 0.7, decay_days: 270,
    description: 'התרחבות גיאוגרפית מייצרת צורך בתשתיות, לוקליזציה, שרשרת אספקה וכוח אדם.',
    keywords: ['התרחבות', 'expansion', 'שוק חדש', 'סניף חדש', 'מפעל חדש', 'מרכז לוגיסטי', 'global', 'בינלאומי'] },
  { code: 'major_contract', name_he: 'זכייה בחוזה או מכרז גדול', name_en: 'Major contract win', category: 'market', base_weight: 0.7, decay_days: 240,
    description: 'זכייה גדולה מחייבת סקייל תפעולי מהיר — כוח אדם, מערכות ותשתיות.',
    keywords: ['זכתה', 'מכרז', 'חוזה', 'tender', 'contract', 'RFP', 'הזמנה', 'עסקה גדולה'] },
  { code: 'rfp_published', name_he: 'פרסום מכרז / RFP טכנולוגי', name_en: 'RFP published', category: 'market', base_weight: 0.9, decay_days: 90,
    description: 'מכרז פתוח — הזדמנות מיידית עם לוח זמנים ידוע.',
    keywords: ['מכרז פומבי', 'RFP', 'RFI', 'בקשה להצעות', 'פנייה לקבלת מידע', 'מנהל הרכש'] },
  { code: 'partnership', name_he: 'שותפות אסטרטגית', name_en: 'Strategic partnership', category: 'market', base_weight: 0.5, decay_days: 180,
    description: 'שותפות חדשה גוררת אינטגרציות ומערכות משותפות.',
    keywords: ['שותפות', 'partnership', 'שיתוף פעולה', 'alliance', 'JV', 'מיזם משותף'] },
  { code: 'service_crisis', name_he: 'משבר שירות / תלונות לקוחות', name_en: 'Service crisis', category: 'market', base_weight: 0.7, decay_days: 150,
    description: 'קריסת מוקד או גל תלונות — צורך בניהול ידע, שירות עצמי ואוטומציה.',
    keywords: ['תלונות', 'משבר שירות', 'זמן המתנה', 'מוקד קרס', 'שביתה במוקד', 'complaints', 'הרשות להגנת הצרכן'] },
];

// ═══════════════════════════════════════════════════════════════════════
//  מיפוי טריגר → חברת בת / שירות, עם משקל והנמקה
//  (subsidiarySlug, triggerCode, serviceSlug | null, weight, rationale)
// ═══════════════════════════════════════════════════════════════════════
export const SUBSIDIARY_TRIGGERS = [
  // Eternity — דאטה, BI, AI
  ['eternity', 'data_platform_project', 'data-platform', 0.95, 'פרויקט מחסן נתונים הוא בדיוק הליבה של איטרניטי.'],
  ['eternity', 'ai_initiative', 'gen-ai', 0.9, 'יוזמת AI נכשלת בלי תשתית דאטה נקייה — נקודת הכניסה של איטרניטי.'],
  ['eternity', 'merger_acquisition', 'data-platform', 0.8, 'מיזוג מחייב איחוד ומיגרציה של מאגרי נתונים משתי החברות.'],
  ['eternity', 'regulatory_pressure', 'data-governance', 0.8, 'רגולציית פרטיות/דיווח דורשת ממשל נתונים ומעקב מוצא נתונים.'],
  ['eternity', 'ipo_listing', 'bi-analytics', 0.75, 'חברה ציבורית חייבת דיווח פיננסי אמין ודשבורדים לדירקטוריון.'],
  ['eternity', 'earnings_growth', 'bi-analytics', 0.5, 'צמיחה מייצרת תקציב לשדרוג יכולות אנליטיקה.'],
  ['eternity', 'core_system_replacement', 'data-platform', 0.75, 'החלפת ERP/CRM גוררת מיגרציית נתונים ובניית שכבת דיווח מחדש.'],
  ['eternity', 'cost_efficiency', 'data-science-ml', 0.6, 'התייעלות מונעת מנתונים — מודלי חיזוי לאופטימיזציה תפעולית.'],

  // Aman Cyber & Cloud
  ['aman-cyber-cloud', 'cyber_incident', 'infosec', 0.98, 'אירוע סייבר מייצר תקציב חירום מיידי להגנה ולשיקום.'],
  ['aman-cyber-cloud', 'cyber_incident', 'backup-dr', 0.9, 'אחרי מתקפת כופר, גיבוי ו-DR הופכים לסעיף הראשון בתקציב.'],
  ['aman-cyber-cloud', 'cloud_migration', 'cloud-migration', 0.95, 'התאמה ישירה: מיגרציה וניהול ענן.'],
  ['aman-cyber-cloud', 'regulatory_pressure', 'compliance-hardening', 0.85, 'תקנים כמו ISO 27001 ותיקון 13 דורשים הקשחות וביקורת.'],
  ['aman-cyber-cloud', 'audit_finding', 'compliance-hardening', 0.85, 'ממצא ביקורת מחייב תיקון עם דדליין — פרויקט מובטח.'],
  ['aman-cyber-cloud', 'merger_acquisition', 'it-integration', 0.8, 'מיזוג = איחוד דומיינים, זהויות, רשתות ומרכזי נתונים.'],
  ['aman-cyber-cloud', 'ipo_listing', 'compliance-hardening', 0.7, 'הנפקה מחייבת בקרות אבטחה ברמה של חברה ציבורית.'],
  ['aman-cyber-cloud', 'market_expansion', 'it-integration', 0.6, 'אתר או שוק חדש דורש תשתיות ורשת מקומית.'],

  // Innocom
  ['innocom', 'cyber_incident', 'security-products', 0.85, 'אחרי אירוע — רכש מואץ של מוצרי הגנה ורישוי.'],
  ['innocom', 'cloud_migration', 'networking', 0.7, 'מיגרציה לענן דורשת ADC, איזון עומסים ואבטחת תעבורה.'],
  ['innocom', 'reorg', 'digital-workplace', 0.65, 'שינוי ארגוני / עבודה היברידית = פרויקט VDI ועמדות עבודה.'],
  ['innocom', 'hiring_surge_it', 'digital-workplace', 0.6, 'גידול מהיר במצבת העובדים מחייב הקמת עמדות עבודה בקנה מידה.'],
  ['innocom', 'regulatory_pressure', 'security-products', 0.65, 'רגולציה מתרגמת לרשימת בקרות טכנולוגיות שצריך לרכוש.'],

  // Aman Digital
  ['aman-digital', 'new_digital_product', 'web-app-dev', 0.95, 'השקת אתר/אפליקציה — הליבה של אמן דיגיטל.'],
  ['aman-digital', 'digital_transformation', 'digital-strategy', 0.9, 'תוכנית טרנספורמציה נפתחת באסטרטגיה דיגיטלית ומיפוי מסע לקוח.'],
  ['aman-digital', 'core_system_replacement', 'lowcode-outsystems', 0.75, 'החלפת מערכת ליבה — OutSystems מקצר משמעותית את זמן ההטמעה.'],
  ['aman-digital', 'service_crisis', 'ux-ui', 0.75, 'גל תלונות לרוב מתחיל בחוויית משתמש שבורה באזור האישי.'],
  ['aman-digital', 'ipo_listing', 'digital-marketing', 0.55, 'הנפקה מחייבת נוכחות דיגיטלית ומסרים מותאמים למשקיעים.'],
  ['aman-digital', 'market_expansion', 'web-app-dev', 0.7, 'שוק חדש = לוקליזציה, אתר בשפה נוספת ותהליכי המרה מקומיים.'],
  ['aman-digital', 'ai_initiative', 'digital-strategy', 0.6, 'יוזמות AI פונות ללקוח דרך ממשק — צריך עיצוב ותכנון חוויה.'],

  // KMS Lighthouse
  ['kms-lighthouse', 'service_crisis', 'agent-knowledge', 0.95, 'משבר שירות = זמני טיפול ארוכים ותשובות לא עקביות. בדיוק מה ש-KMS פותרת.'],
  ['kms-lighthouse', 'ai_initiative', 'knowledge-ai', 0.85, 'GenAI ארגוני חייב מקור ידע מהימן — אחרת הוא ממציא תשובות.'],
  ['kms-lighthouse', 'hiring_surge_it', 'onboarding-training', 0.75, 'גיוס מסיבי מייצר עומס קליטה והדרכה שניהול ידע מקצר.'],
  ['kms-lighthouse', 'regulatory_pressure', 'agent-knowledge', 0.8, 'רגולציה מחייבת שכל נציג ייתן את אותה תשובה מדויקת ומתועדת.'],
  ['kms-lighthouse', 'cost_efficiency', 'self-service', 0.8, 'הסטת פניות לשירות עצמי היא חיסכון ישיר בעלות מוקד.'],
  ['kms-lighthouse', 'merger_acquisition', 'agent-knowledge', 0.7, 'מיזוג = שני מאגרי ידע וסט נהלים כפול שצריך לאחד.'],

  // Asperii
  ['asperii', 'core_system_replacement', 'salesforce-crm', 0.9, 'החלפת CRM — אספרי היא משווקת ומטמיעה מורשית של Salesforce בישראל.'],
  ['asperii', 'market_expansion', 'salesforce-fsl', 0.8, 'התרחבות גיאוגרפית מכפילה את מורכבות ניהול הטכנאים בשטח.'],
  ['asperii', 'service_crisis', 'salesforce-fsl', 0.85, 'עיכובים בשירות בשטח נפתרים בתיאום וניתוב אוטומטי של טכנאים.'],
  ['asperii', 'cost_efficiency', 'workforce-mgmt', 0.8, 'אופטימיזציית מסלולים וזמני טכנאי היא חיסכון תפעולי מדיד.'],
  ['asperii', 'merger_acquisition', 'salesforce-crm', 0.7, 'מיזוג מחייב איחוד של שתי מערכות CRM ובסיסי לקוחות.'],
  ['asperii', 'new_digital_product', 'servicemax', 0.6, 'מוצר פיזי חדש גורר מערך תחזוקה ושירות לנכסים מותקנים.'],

  // Veriest
  ['veriest', 'funding_round', 'design-verification', 0.9, 'סטארטאפ שבבים אחרי גיוס צריך להאיץ טייפ-אאוט — אימות הוא צוואר הבקבוק.'],
  ['veriest', 'hiring_surge_it', 'asic-fpga-design', 0.8, 'משרות VLSI פתוחות רבות = מחסור בכוח אדם שצוות חיצוני פותר מיד.'],
  ['veriest', 'new_digital_product', 'design-verification', 0.75, 'דור שבב חדש דורש מחזור אימות מלא.'],
  ['veriest', 'major_contract', 'backend-dft', 0.7, 'חוזה גדול מחייב עמידה בלוח זמנים לטייפ-אאוט.'],
  ['veriest', 'partnership', 'formal-verification', 0.5, 'שיתוף פעולה על IP מחייב אימות פורמלי של הממשקים.'],

  // Aman Group (core)
  ['aman-group', 'hiring_surge_it', 'tech-recruitment', 0.9, 'ריבוי משרות פתוחות הוא הסימן הישיר ביותר לצורך בגיוס ומיקור חוץ.'],
  ['aman-group', 'cost_efficiency', 'outsourcing', 0.8, 'מיקור חוץ ממיר עלות קבועה בעלות משתנה — טיעון ישיר בתוכנית התייעלות.'],
  ['aman-group', 'major_contract', 'managed-teams', 0.75, 'זכייה גדולה דורשת סקייל מהיר של צוותים.'],
  ['aman-group', 'funding_round', 'tech-recruitment', 0.7, 'הון טרי מתורגם קודם כול לגיוס עובדים.'],
  ['aman-group', 'market_expansion', 'managed-teams', 0.6, 'התרחבות דורשת צוות מקומי או ODC ייעודי.'],

  // Rasner
  ['rasner', 'market_expansion', 'supply-chain-sw', 0.8, 'שוק או מרכז לוגיסטי חדש מכפיל את מורכבות שרשרת האספקה.'],
  ['rasner', 'cost_efficiency', 'demand-planning', 0.8, 'עודפי מלאי הם היעד הראשון בכל תוכנית התייעלות קמעונאית או תעשייתית.'],
  ['rasner', 'major_contract', 'supply-chain-sw', 0.65, 'חוזה אספקה גדול מחייב תכנון ביקושים מדויק.'],

  // Kiddod
  ['kiddod', 'market_expansion', 'material-handling', 0.7, 'מפעל או מסוף חדש מחייב תכנון מערך שינוע.'],
  ['kiddod', 'major_contract', 'industrial-pm', 0.6, 'פרויקט תעשייתי גדול דורש ניהול הקמה.'],

  // DBFS / HCCM / Integral / DeoniX — פעילות בינלאומית
  ['dbfs', 'regulatory_pressure', 'fin-consulting', 0.7, 'רגולציה פיננסית באירופה היא מנוע פרויקטים קבוע.'],
  ['dbfs', 'hiring_surge_it', 'fin-recruitment', 0.7, 'מחסור במומחי שוק הון נפתר בגיוס מומחים.'],
  ['hccm', 'market_expansion', 'nearshore-teams', 0.7, 'התרחבות לאירופה מייצרת צורך בצוות nearshore.'],
  ['hccm', 'cost_efficiency', 'nearshore-teams', 0.75, 'Nearshore בפורטוגל הוא חיסכון ישיר מול עלות פיתוח מקומית.'],
  ['integral-solutions', 'data_platform_project', 'informatica-pl', 0.7, 'פרויקט אינטגרציית נתונים בפולין — Informatica היא הסטנדרט.'],
  ['deonix', 'market_expansion', 'enterprise-solutions-kz', 0.7, 'כניסה לשוק מרכז אסיה דורשת שותף מקומי.'],
  ['deonix', 'data_platform_project', 'data-management-kz', 0.65, 'פרויקטי דאטה אזוריים על גבי Informatica.'],
];

// ═══════════════════════════════════════════════════════════════════════
//  לקוחות ידועים + שיוך לחברת בת (מבוסס מקורות פומביים)
// ═══════════════════════════════════════════════════════════════════════
const SRC_ASPERII = 'https://www.prnewswire.com/il/news-releases/asperii-announces-3m-investment-from-aman-group-fueling-its-global-expansion-in-the-field-service-market-300804101.html';
const SRC_VERIEST = 'https://www.veriests.com/';
const SRC_KMS = 'https://kmslh.com/casestudies/aig/';
const SRC_DIGITAL = 'https://amandigital.co.il/';

export const CLIENTS = [
  { slug: 'ikea-israel', name_he: 'איקאה ישראל', name_en: 'IKEA Israel', industry: 'קמעונאות',
    size_band: 'Enterprise', website: 'https://www.ikea.co.il/',
    links: [{ sub: 'asperii', rel: 'customer', url: SRC_ASPERII, conf: 0.75,
              text: 'נמנית על לקוחות אספרי בישראל לצד סלקום ושטראוס מים.' }] },

  { slug: 'cellcom', name_he: 'סלקום', name_en: 'Cellcom Israel', industry: 'תקשורת',
    size_band: 'Enterprise', is_public: 1, ticker: 'CEL', exchange: 'TASE', website: 'https://www.cellcom.co.il/',
    links: [{ sub: 'asperii', rel: 'customer', url: SRC_ASPERII, conf: 0.75,
              text: 'נמנית על לקוחות אספרי בישראל.' }] },

  { slug: 'strauss-water', name_he: 'שטראוס מים', name_en: 'Strauss Water', industry: 'מוצרי צריכה',
    size_band: 'Mid', website: 'https://www.strauss-water.co.il/',
    links: [{ sub: 'asperii', rel: 'customer', url: SRC_ASPERII, conf: 0.75,
              text: 'נמנית על לקוחות אספרי בישראל.' }] },

  { slug: 'shufersal', name_he: 'שופרסל', name_en: 'Shufersal', industry: 'קמעונאות',
    size_band: 'Enterprise', is_public: 1, ticker: 'SAE', exchange: 'TASE', website: 'https://www.shufersal.co.il/',
    links: [{ sub: 'aman-digital', rel: 'customer', url: SRC_DIGITAL, conf: 0.7,
              text: 'מוצגת כמותג מוביל שאמן דיגיטל מספקת לו פתרון 360°.' }] },

  { slug: 'bank-hapoalim', name_he: 'בנק הפועלים', name_en: 'Bank Hapoalim', industry: 'פיננסים',
    size_band: 'Enterprise', is_public: 1, ticker: 'POLI', exchange: 'TASE', website: 'https://www.bankhapoalim.co.il/',
    links: [{ sub: 'aman-digital', rel: 'customer', url: SRC_DIGITAL, conf: 0.7,
              text: 'מוצג כלקוח של אמן דיגיטל בפתרונות דיגיטל מקצה לקצה.' }] },

  { slug: 'paz-yellow', name_he: 'פז / Yellow', name_en: 'Paz (Yellow)', industry: 'אנרגיה וקמעונאות',
    size_band: 'Enterprise', is_public: 1, ticker: 'PZOL', exchange: 'TASE', website: 'https://www.paz.co.il/',
    links: [{ sub: 'aman-digital', rel: 'customer', url: SRC_DIGITAL, conf: 0.65,
              text: 'רשת Yellow מוצגת כלקוחה של אמן דיגיטל.' }] },

  { slug: 'aig-israel', name_he: 'AIG ישראל', name_en: 'AIG Israel', industry: 'ביטוח',
    size_band: 'Mid', website: 'https://www.aig.co.il/',
    links: [{ sub: 'kms-lighthouse', rel: 'case_study', url: SRC_KMS, conf: 0.9,
              text: 'Case study רשמי: KMS Lighthouse אפשרה לסוכנים למצוא תשובות מדויקות ואחידות ולהגדיל מכירות.' }] },

  { slug: 'clal-insurance', name_he: 'כלל ביטוח', name_en: 'Clal Insurance', industry: 'ביטוח',
    size_band: 'Enterprise', is_public: 1, ticker: 'CLIS', exchange: 'TASE', website: 'https://www.clalbit.co.il/',
    links: [{ sub: 'kms-lighthouse', rel: 'customer', url: 'https://kmslh.com/', conf: 0.7,
              text: 'נמנית על חברות הביטוח המובילות שעובדות עם KMS Lighthouse.' }] },

  { slug: 'ayalon-insurance', name_he: 'איילון ביטוח', name_en: 'Ayalon Insurance', industry: 'ביטוח',
    size_band: 'Mid', website: 'https://www.ayalon-ins.co.il/',
    links: [{ sub: 'kms-lighthouse', rel: 'customer', url: 'https://kmslh.com/', conf: 0.7,
              text: 'נמנית על חברות הביטוח שעובדות עם KMS Lighthouse.' }] },

  { slug: 'bank-discount', name_he: 'בנק דיסקונט', name_en: 'Israel Discount Bank', industry: 'פיננסים',
    size_band: 'Enterprise', is_public: 1, ticker: 'DSCT', exchange: 'TASE', website: 'https://www.discountbank.co.il/',
    links: [{ sub: 'kms-lighthouse', rel: 'customer', url: 'https://kmslh.com/news/kms-lighthouse-completed-a-roadshow-with-its-partner-microsoft-in-4-cities-around-the-world-orlando-london-tel-aviv-and-dallas', conf: 0.6,
              text: 'הופיע כמרצה אורח באירוע משותף של KMS Lighthouse ומיקרוסופט.' }] },

  { slug: 'marvell', name_he: 'מארוול', name_en: 'Marvell Semiconductor', industry: 'שבבים',
    size_band: 'Enterprise', is_public: 1, ticker: 'MRVL', exchange: 'NASDAQ', country: 'US',
    website: 'https://www.marvell.com/',
    links: [{ sub: 'veriest', rel: 'customer', url: SRC_VERIEST, conf: 0.7,
              text: 'מופיעה בין לקוחות ורייאסט.' }] },

  { slug: 'ceva', name_he: 'CEVA', name_en: 'CEVA Inc.', industry: 'שבבים',
    size_band: 'Mid', is_public: 1, ticker: 'CEVA', exchange: 'NASDAQ', website: 'https://www.ceva-ip.com/',
    links: [{ sub: 'veriest', rel: 'case_study', url: 'https://www.veriests.com/news-and-press/veriest-solutions-and-ceva-collaborate-for-neural-network-signal-processing-ip-project/', conf: 0.9,
              text: 'הודעה רשמית על שיתוף פעולה בפרויקט IP לעיבוד אותות לרשתות נוירונים.' }] },

  { slug: 'valens', name_he: 'ולנס', name_en: 'Valens Semiconductor', industry: 'שבבים',
    size_band: 'Mid', is_public: 1, ticker: 'VLN', exchange: 'NYSE', website: 'https://www.valens.com/',
    links: [{ sub: 'veriest', rel: 'customer', url: SRC_VERIEST, conf: 0.7,
              text: 'מופיעה בין לקוחות ורייאסט.' }] },

  { slug: 'synopsys', name_he: 'סינופסיס', name_en: 'Synopsys', industry: 'שבבים / EDA',
    size_band: 'Enterprise', is_public: 1, ticker: 'SNPS', exchange: 'NASDAQ', country: 'US',
    website: 'https://www.synopsys.com/',
    links: [{ sub: 'veriest', rel: 'customer', url: SRC_VERIEST, conf: 0.7,
              text: 'מופיעה בין לקוחות ורייאסט.' }] },
];
